### ISSUE TITLE
`executemany` with `None` values raising `pyo3_runtime.PanicException: not yet implemented`

### ISSUE THREAD

**Issue by hbmartin** [tursodatabase/libsql-experimental-python#65]
Works as expected when values are present.
Python 3.12.4 on MacOS 14.5 with libsql-experimental==0.0.34
```

thread '<unnamed>' panicked at src/lib.rs:411:39:
not yet implemented
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: libsql_experimental::execute::{{closure}}
   4: tokio::runtime::park::CachedParkThread::block_on
   5: tokio::runtime::context::runtime::enter_runtime
   6: tokio::runtime::runtime::Runtime::block_on
   7: libsql_experimental::_::<impl libsql_experimental::Connection>::__pymethod_executemany__
   8: pyo3::impl_::trampoline::trampoline
   9: libsql_experimental::_::<impl pyo3::impl_::pyclass::PyMethods<libsql_experimental::Connection> for pyo3::impl_::pyclass::PyClassImplCollector<libsql_experimental::Connection>>::py_methods::ITEMS::trampoline
  10: _method_vectorcall_FASTCALL_KEYWORDS
  11: __PyEval_EvalFrameDefault
  12: _PyEval_EvalCode
  13: _builtin_exec
  14: _cfunction_vectorcall_FASTCALL_KEYWORDS
  15: __PyEval_EvalFrameDefault
  16: _pymain_run_module
  17: _Py_RunMain
  18: _pymain_main
  19: _Py_BytesMain
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/haroldmartin/Downloads/safari-to-sqlite/safari_to_sqlite/__main__.py", line 106, in <module>
    main()
  File "/Users/haroldmartin/Downloads/safari-to-sqlite/safari_to_sqlite/__main__.py", line 97, in main
    save(db, auth_path)
  File "/Users/haroldmartin/Downloads/safari-to-sqlite/safari_to_sqlite/__main__.py", line 72, in save
    db.insert_tabs(tabs)
  File "/Users/haroldmartin/Downloads/safari-to-sqlite/safari_to_sqlite/datastore.py", line 79, in insert_tabs
    self.con.executemany(insert, tabs)
pyo3_runtime.PanicException: not yet implemented
```

**Comment by SirCraft007** [comment]
This also works as expected if values are present, but if it's None it returns this error
libsql-experimental==0.0.41
Python 3.12.7
MacOS 15.2
`Traceback (most recent call last):
  File "/Users/serafino/Documents/VS code/grade-api/init.py", line 120, in <module>
    cur.executemany(
ValueError: Unsupported parameter type`
